theme = "onedark"

[editor]
line-number = "relative"
scroll-lines = 1
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
# Move lines up and down
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# Open Lazygit in a popup window
# To start tmux with iTerm2:
# iTerm2 > Preferences > Profiles > General > Command > Send text at start
# `tmux ls && read tmux_session && tmux attach -t ${tmux_session:-default} || tmux new -s ${tmux_session:-default}`
C-g = ":sh tmux new-session -d \\; popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"

